### ISSUE TITLE
Docker版支付宝账单导入问题

### ISSUE THREAD

**Issue by TingXuanZhang** [Nicholas-cool/P4_MoneyArrangeModule#3]
### 问题
支付宝账单无法正常导入，日志显示Python不支持ANSI格式编码

## 具体报错信息
```
[04/Apr/2024 16:26:52] "POST /e_upload_bill/ HTTP/1.1" 500 57920
Internal Server Error: /e_upload_bill/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/app/P4_MoneyArrangeModule/e__money_arrange_function/e_upload_bill.py", line 186, in e_upload_bill
    file_content = upload_file.read().decode('ansi')  # 获取文件内容
LookupError: unknown encoding: ansi
```

**Comment by Nicholas-cool** [comment]
可能是MAC系统上运行的问题，可以将该行的`ansi`修改为`gbk`试一下

**Comment by TingXuanZhang** [comment]
感谢回复，不过我是在一台Debian 11的LXC上部署的docker，目前我进入容器内部使用
`sed -i "s/upload_file.read().decode('ansi')/upload_file.read().decode('utf-8')/" e_upload_bill.py`
已经解决了这个问题

**Comment by Nicholas-cool** [comment]
好的，后续版本会在这里新增异常判断。

**Comment by Victorcui1023** [comment]
我也遇到了同样问题，支付宝账单显示不支持ANSI，希望尽快解决，越做越好，加油！

---------------
后面在Docker 把支付宝解码格式从'ansi'改成’gbk‘解决了问题
