### ISSUE TITLE
docker 运行失败：

### ISSUE THREAD

**Issue by whr819987540** [Nicholas-cool/P4_MoneyArrangeModule#4]
日志如下：

```bash
root@whr:~# docker run -d \
> -p 9008:9008 \
> -v p4_money_arrange_module:/usr/src/app \
> -e DJANGO_SUPERUSER_PASSWORD=money_arrange \
> --name p4_money_arrange_module \
> nicholascool/p4_money_arrange_module:1.1.5
ac796f6a14a6745571a6577e2939a17dd8a6c1ccb541776832615c0e654ecd80
root@whr:~# docker logs p4_money_arrange_module
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
CommandError: Error: That username is already taken.
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 22, in <module>
    main()
  File "/usr/src/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 96, in handle
    self.run(**options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 640, in run_with_reloader
    exit_code = restart_with_reloader()
  File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 259, in restart_with_reloader
    p = subprocess.run(args, env=new_environ, close_fds=False)
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1751, in _execute_child
    self._posix_spawn(args, executable, env, restore_signals,
  File "/usr/local/lib/python3.10/subprocess.py", line 1696, in _posix_spawn
    self.pid = os.posix_spawn(executable, args, env, **kwargs)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/bin/python'
```

**Comment by whr819987540** [comment]
加上`--privileged`即可
